apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  minReadySeconds: 60    
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: nginx     
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          requests:
            cpu: "0.5"
          limits:
            cpu: "1"
        env:
        - name: thread
          valueFrom:
            configMapKeyRef:
              name: nginx-environment-variables          
              key: thread
        - name: interface
          valueFrom:
            configMapKeyRef:
              name: nginx-environment-variables          
              key: interface      
        ports:
        - containerPort: 80
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  type: ClusterIP
  ports:
  - protocol: TCP
    targetPort: 8983
    port: 8081          


