apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginxapp
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/yeswanth9171/Deployments.git
    targetRevision: HEAD
    path: Deployments/Nginx/Deployment
  destination:
    server: https://kubernetes.default.svc
    namespace: ns-nginx
    
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    
    automated:
      selfHeal: true
      prune: true
      
      
    
